### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by Mesona** [Mesona/Places#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production
---
## Comments
* There should be a link in the Sign Up modal that links the the Login modal, and vice versa. After this is implemented, make sure that errors do not persist when switching between the two.
* The Login/Signup Forms are pretty bland at the moment. I would try to emulate Google's sign-in form (except you can have the email and password on one page instead of having an email form, which leads to a password form, which leads to being logged in). The recruiters doing the first pass over your app are going to care a lot about styling and the site looking nice over functionality. Having bigger inputs, with rounded corners, that change colors on `:hover` and `:focus` goes a long way. Also adding color to the `Log In` and `Sign Up` buttons themselves and changing the shade upon hover is a must.
![screen shot 2019-02-28 at 3 14 06 pm](https://user-images.githubusercontent.com/32026924/53605191-8dea6900-3b6b-11e9-84bb-c009240846cc.png)
![screen shot 2019-02-28 at 2 40 39 pm](https://user-images.githubusercontent.com/32026924/53605218-a8244700-3b6b-11e9-9c15-68e678153921.png)
* It would be nice if the demo login button didn't just pre-fill the form, but also actually logged me in.
* Anything that is clickable should have the CSS property `cursor: pointer;` on it. This is a simple thing that greatly improves UI.
* These buttons are pretty ugly. I get that it's going to be different than Google's actual site since all of their stuff is linked to people's Google account, but it would look better if you got rid of the default styling, and made them look more like links, with a similar color scheme to the rest of your website. I would recommend having them all in one row as well as opposed to the way they're stacked on top of each other right now.
![screen shot 2019-02-28 at 2 15 41 pm](https://user-images.githubusercontent.com/32026924/53602770-99866180-3b64-11e9-8b10-2c498413ff46.png)
* This isn't part of user auth so this won't affect closing out this issue, but you should eventually style this dropdown to more closely match the style of googles (dropdown appears slightly below, has it's own box which is not highlighted, etc.)
![screen shot 2019-02-28 at 2 24 57 pm](https://user-images.githubusercontent.com/32026924/53602971-1dd8e480-3b65-11e9-8fd3-520389d6e301.png)
![screen shot 2019-02-28 at 2 25 02 pm](https://user-images.githubusercontent.com/32026924/53602972-1dd8e480-3b65-11e9-9da0-f6f154361b73.png)

**Comment by ronilbhatia** [comment]
Hey Kyle,

Good job getting User Auth set up! I left a few comments mostly related to styling. The last comment isn't one that is necessary to close out this issue, but is something you should fix before you submit your project next Friday. Let me know once you've addressed all the comments!

**Comment by Mesona** [comment]
Everything except the dropdown has been addressed, but I'll get to that when I get to place permission settings.

**Comment by ronilbhatia** [comment]
Awesome, styling looks a lot better! There are a few funky things going on functionality wise, though.
* When I press 'enter' on the signup or login form, instead of submitting the form data it redirects me to the login page if i was on signup and vice versa. You should make sure the actual button to submit the form button is the only input with type of 'submit' and that your form has an `onSubmit` event handler. I think if you do those two things it use the form submission button instead of the button to switch modals.
* I'm not seeing errors rendered to the screen for 'Sign Up'. Make sure that errors are displayed when there are problems with the sign up - also I can't tell for sure right now since it seems like you aren't rendering errors in your signup form, but errors should disappear when switching between the signup and login forms. This can be easily achieved by adding a `componentWillUnmount` and invoking the `clearErrors` function you should have defined in your session actions.

Overall though, site is looking great. Once these two points are addressed I can close the issue!

**Comment by ronilbhatia** [comment]
Thanks for addressing everything! Closing this out.
